# Copyright 2026 Forge-Code contributors
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pathlib import Path
from typing import Any

from forge_code.context import git_summary
from forge_code.ignore import IgnoreMatcher
from forge_code.qa.runner import detect_checks

CONTEXT_REL = Path(".forge") / "context.md"
MAX_CONTEXT = 8_000


def context_path(root: Path) -> Path:
    return root / CONTEXT_REL


def load_context(root: Path, limit: int = MAX_CONTEXT) -> str:
    path = context_path(root)
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")[:limit]


def save_context(root: Path) -> Path:
    path = context_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_context(root), encoding="utf-8")
    return path


def ensure_context(root: Path) -> str:
    if not context_path(root).is_file():
        save_context(root)
    return load_context(root)


def render_context(root: Path) -> str:
    matcher = IgnoreMatcher(root)
    stacks = _stacks(root)
    checks = detect_checks(root)
    layout = _layout(root, matcher)
    title = _readme_title(root)
    lines = [
        "# Forge project context",
        "",
        "Generated by Forge. Safe to commit. Refresh with `forge context` or the `project_map` tool.",
        "Do not put secrets here.",
        "",
        f"- root: `{root.name}`",
    ]
    if title:
        lines.append(f"- title: {title}")
    lines.append(f"- stack: {', '.join(stacks) or '(unknown)'}")
    if checks:
        lines.append("- tests:")
        for name, _cmd in checks:
            lines.append(f"  - {name}")
    else:
        lines.append("- tests: (none detected)")
    lines.extend(["", "## Layout", ""])
    lines.extend(f"- `{name}`" for name in layout or ["(empty)"])
    lines.extend(["", "## Git", "", git_summary(root), ""])
    return "\n".join(lines)[:MAX_CONTEXT]


def project_map(root: Path, _args: dict[str, Any]) -> str:
    path = save_context(root)
    rel = path.relative_to(root).as_posix()
    return f"wrote {rel}\n\n" + load_context(root)


def _stacks(root: Path) -> list[str]:
    found: list[str] = []
    if (root / "pyproject.toml").exists() or (root / "setup.py").exists() or any(root.glob("*.py")):
        found.append("python")
    if (root / "package.json").exists():
        found.append("node")
    if (root / "Cargo.toml").exists():
        found.append("rust")
    if (root / "go.mod").exists():
        found.append("go")
    if (root / "Makefile").exists():
        found.append("make")
    return found


def _layout(root: Path, matcher: IgnoreMatcher, limit: int = 32) -> list[str]:
    names: list[str] = []
    try:
        entries = sorted(root.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
    except OSError:
        return names
    for path in entries:
        rel = path.name
        if rel.startswith(".") and rel not in {".github", ".forgeignore"}:
            continue
        if path.is_dir() and (matcher.ignored(rel) or matcher.ignored(rel + "/")):
            continue
        if path.is_file() and matcher.ignored(rel):
            continue
        names.append(rel + ("/" if path.is_dir() else ""))
        if len(names) >= limit:
            names.append("…")
            break
    return names


def _readme_title(root: Path) -> str:
    for name in ("README.md", "README"):
        path = root / name
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")[:2_000]
        except OSError:
            continue
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()[:120]
    return ""
