# Copyright 2026 Forge-Code contributors
# SPDX-License-Identifier: Apache-2.0

"""Project context: ``.forge/context.md``.

Forge writes a compact map of the repo (stack, tests, layout, git, scripts,
entry points) so the next session does not re-scan from zero. Refresh when
``pyproject.toml`` / ``package.json`` / etc. are newer than the file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from forge_code.context import git_recent, git_summary
from forge_code.ignore import IgnoreMatcher
from forge_code.qa.runner import detect_checks

CONTEXT_REL = Path(".forge") / "context.md"
MAX_CONTEXT = 8_000
MARKERS = (
    "pyproject.toml",
    "package.json",
    "Cargo.toml",
    "go.mod",
    "Makefile",
    "README.md",
    "README",
)


def context_path(root: Path) -> Path:
    return root / CONTEXT_REL


def load_context(root: Path, limit: int = MAX_CONTEXT) -> str:
    path = context_path(root)
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")[:limit]


def save_context(root: Path) -> Path:
    path = context_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_context(root), encoding="utf-8")
    return path


def is_stale(root: Path) -> bool:
    """True if missing, or a marker file is newer than context.md."""
    path = context_path(root)
    if not path.is_file():
        return True
    try:
        ctx_mtime = path.stat().st_mtime
    except OSError:
        return True
    for name in MARKERS:
        marker = root / name
        if not marker.is_file():
            continue
        try:
            if marker.stat().st_mtime > ctx_mtime:
                return True
        except OSError:
            continue
    return False


def ensure_context(root: Path, *, force: bool = False) -> str:
    """Write if missing or stale vs markers. ``force`` always regenerates."""
    if force or is_stale(root):
        save_context(root)
    return load_context(root)


def refresh_if_markers(root: Path, writes: list) -> None:
    """After agent writes, refresh if a stack marker was touched."""
    names = {Path(str(getattr(w, "path", w) or "")).name for w in writes}
    if names & set(MARKERS):
        save_context(root)


def render_context(root: Path) -> str:
    matcher = IgnoreMatcher(root)
    stacks = _stacks(root)
    checks = detect_checks(root)
    layout = _layout(root, matcher)
    title = _readme_title(root)
    scripts = _scripts(root)
    entry = _entry_points(root)
    langs = _languages(root, matcher)
    recent = git_recent(root, count=5)
    lines = [
        "# Forge project context",
        "",
        "Generated by Forge. Safe to commit. Refresh with `forge context` or the `project_map` tool.",
        "Do not put secrets here. Auto-refreshes when stack markers change.",
        "",
        f"- root: `{root.name}`",
    ]
    if title:
        lines.append(f"- title: {title}")
    lines.append(f"- stack: {', '.join(stacks) or '(unknown)'}")
    lines.append(f"- languages: {langs}")
    if checks:
        lines.append("- tests:")
        for name, _cmd in checks:
            lines.append(f"  - {name}")
    else:
        lines.append("- tests: (none detected)")
    lines.extend(["", "## Layout", ""])
    lines.extend(f"- `{name}`" for name in layout or ["(empty)"])
    lines.extend(["", "## Entry points", ""])
    lines.extend(f"- `{name}`" for name in entry or ["(none guessed)"])
    lines.extend(["", "## Scripts / packages", ""])
    lines.extend(f"- {item}" for item in scripts or ["(none)"])
    lines.extend(["", "## Git", "", git_summary(root)])
    if recent:
        lines.extend(["", "recent:"])
        lines.extend(f"- {line}" for line in recent)
    lines.append("")
    return "\n".join(lines)[:MAX_CONTEXT]


def project_map(root: Path, _args: dict[str, Any]) -> str:
    path = save_context(root)
    rel = path.relative_to(root).as_posix()
    return f"wrote {rel}\n\n" + load_context(root)


def _stacks(root: Path) -> list[str]:
    found: list[str] = []
    if (root / "pyproject.toml").exists() or (root / "setup.py").exists() or any(root.glob("*.py")):
        found.append("python")
    if (root / "package.json").exists():
        found.append("node")
    if (root / "Cargo.toml").exists():
        found.append("rust")
    if (root / "go.mod").exists():
        found.append("go")
    if (root / "Makefile").exists():
        found.append("make")
    return found


def _layout(root: Path, matcher: IgnoreMatcher, limit: int = 32) -> list[str]:
    names: list[str] = []
    try:
        entries = sorted(root.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
    except OSError:
        return names
    for path in entries:
        rel = path.name
        if rel.startswith(".") and rel not in {".github", ".forgeignore"}:
            continue
        if path.is_dir() and (matcher.ignored(rel) or matcher.ignored(rel + "/")):
            continue
        if path.is_file() and matcher.ignored(rel):
            continue
        names.append(rel + ("/" if path.is_dir() else ""))
        if len(names) >= limit:
            names.append("…")
            break
    return names


def _readme_title(root: Path) -> str:
    for name in ("README.md", "README"):
        path = root / name
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")[:2_000]
        except OSError:
            continue
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()[:120]
    return ""


def _scripts(root: Path) -> list[str]:
    out: list[str] = []
    py = root / "pyproject.toml"
    if py.is_file():
        try:
            text = py.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        in_scripts = False
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("[") and "scripts" in stripped.lower():
                in_scripts = True
                continue
            if in_scripts:
                if stripped.startswith("["):
                    break
                if "=" in stripped and not stripped.startswith("#"):
                    name = stripped.split("=", 1)[0].strip().strip("\"'")
                    if name:
                        out.append(f"{name} (pyproject)")
        pkg = root / "src"
        if pkg.is_dir():
            for init in list(pkg.glob("*/__init__.py"))[:4]:
                out.append(f"package {init.parent.name}/")
    pkg_json = root / "package.json"
    if pkg_json.is_file():
        try:
            import json

            data = json.loads(pkg_json.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            data = {}
        if isinstance(data, dict):
            scripts = data.get("scripts")
            if isinstance(scripts, dict):
                for name in list(scripts)[:8]:
                    out.append(f"npm run {name}")
            main = data.get("main") or data.get("bin")
            if main:
                out.append(f"node entry {main}")
    return out[:12]


def _entry_points(root: Path) -> list[str]:
    names = (
        "src/forge_code/cli.py",
        "src/index.ts",
        "src/index.js",
        "src/main.rs",
        "src/main.go",
        "main.py",
        "app.py",
        "index.ts",
        "index.js",
        "cmd/main.go",
    )
    return [name for name in names if (root / name).is_file()][:6]


def _languages(root: Path, matcher: IgnoreMatcher) -> str:
    counts: dict[str, int] = {}
    walked = 0
    for path in root.rglob("*"):
        walked += 1
        if walked > 2500:
            break
        if not path.is_file():
            continue
        if not matcher.allowed_file(path):
            continue
        ext = path.suffix.lower()
        if ext in {".py", ".ts", ".tsx", ".js", ".jsx", ".rs", ".go", ".java", ".rb", ".md"}:
            counts[ext] = counts.get(ext, 0) + 1
        if sum(counts.values()) >= 400:
            break
    if not counts:
        return "(none counted)"
    parts = [f"{ext} {n}" for ext, n in sorted(counts.items(), key=lambda item: -item[1])[:6]]
    return ", ".join(parts)
